### PR TITLE
port-javascript: add sync file access for scripts compatibility

### PR DESCRIPTION
**Pull request by pmp-p**
activate with ```emmake make WASM_FILE_API=1```

### CODE REVIEW

**Comment by amirgon** [comment]
@pmp-p Would that work for `import`?

**Comment by pmp-p** [comment]
@amirgon no,
only for open() like :
open('localfile) open('://somefile')  open('http://site/remote.file') open('https://site/remote.file')

**Comment by amirgon** [comment]
> @amirgon no,
> only for open() like :
> open('localfile) open('://somefile') open('http://site/remote.file') open('https://site/remote.file')

Actually, `import` is even more important.
What would it take to support `import` as well?

**Comment by pmp-p** [comment]
@amirgon i can look into it, but i can tell you already that it will require that fix https://github.com/micropython/micropython/pull/4860 to keep script compatibility.

**Comment by amirgon** [comment]
> @amirgon i can look into it, but i can tell you already that it will require that fix [micropython#4860](https://github.com/micropython/micropython/pull/4860) to keep script compatibility.

@pmp-p Could you explain why this is necessary? Why can't we just replace Micropython's native file access, such that all file access (either `open` or `import`) would be terminated by BrowserFS or something similar?

**Comment by pmp-p** [comment]
The fix has nothing to do with file access, it's a weird bug in parser that is raised when using emscripten compiled code i found when adding support for ```import```, importing anything from ramdisk will raise a syntax error.

Using BrowserFS would mean ** all ** file access would go via its backend, including ramdisk libc fd opening. 

Maybe it's overkill both for size (browserfs) and performance (multiple layers) and it certainly add complexity. 

I find the way to open('http(s)://') files via python very handy, i'm not sure lvgl needs remote file access via stdio except in it's pure C/C++ use cases.

File: ports/javascript/wasm_file_api.c [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+// VERY BAD
+int wasm_file_open(const char *url) {
+    fprintf(stderr,"204:wasm_file_open[%s]\n", url);
+
+    if (strlen(url)>1 && url[0]==':') {
+        fprintf(stderr,"  -> same host[%s]\n", url);
+        int fidx = EM_ASM_INT({return wasm_file_open(UTF8ToString($0)); }, url );
+        char fname[256];
+        snprintf(fname, sizeof(fname), "cache_%d", fidx);
```
Comment (embeddedt) [inline ports/javascript/wasm_file_api.c]: The maximum value of `int` is `2147483647` (10 charcters). `cache_` takes up another 6 characters, plus we need 1 for the trailing byte. That brings the minimal buffer size required to 17 characters. I think `char fname[20]` would be more than enough space.

Comment (pmp-p) [reply ports/javascript/wasm_file_api.c]: no you miss nothing, that extra space was for - maybe- replicating path when accessing local file on server in order to possibly do packages/namespace imports ( which was to boring to write in C :D )

maybe makes it the same size as the max path size of micropython vfs in case some1 could write it  ?

Comment (pmp-p) [reply ports/javascript/wasm_file_api.c]: found it, it's  #define MICROPY_ALLOC_PATH_MAX 256 in mpconfigport.h

Comment (embeddedt) [reply ports/javascript/wasm_file_api.c]: @pmp-p That's fine.

**Comment by amirgon** [comment]
> Using BrowserFS would mean ** all ** file access would go via its backend, including ramdisk libc fd opening.
> 

I think that's a good thing, that all file access will go through it. Instead of providing ad-hoc solution for file stream, for import, etc.

> Maybe it's overkill both for size (browserfs) and performance (multiple layers) and it certainly add complexity.

If it has simple enough API, why would it add any complexity? How big is it?

**Comment by pmp-p** [comment]
> How big is it?

228 KiB https://github.com/pmp-p/panda3d-webgl-runtime/blob/master/js/browserfs.p3dwgl.js
but maybe it could be minified or something ...

> I think that's a good thing

Sure ... if you like writing filesystem backends in javascript  and browserify them !

for my part i'd like to have async wasm vfs and adding the matching API to micropython ports with asyncio, because neither the hack in PR or BrowserFS are wasm solutions and in any case sync access is bad pratice and could vanish from browser anytime now https://developers.google.com/web/updates/2012/01/Getting-Rid-of-Synchronous-XHRs .

**Comment by embeddedt** [comment]
228 KiB is really not that large. I think size is not an issue at all.

**Comment by pmp-p** [comment]
hmmm i don't think BrowserFS will like opening remote url, and the init code reminded me it uses a subfolder (mount) in the ramdisk
```function setupBFS() {
  // Constructs an instance of the backed file system.
    var lsfs = new BrowserFS.FileSystem.XmlHttpRequest('directio');
    BrowserFS.initialize(lsfs);

    var BFS = new BrowserFS.EmscriptenFS();

    FS.createFolder(FS.root, '/srv', true, true);
    FS.mount(BFS, {root: '/'}, 'srv');
}
```
that means server addressed files should always starts with the mount path like  ```/srv/file_on_the_server```  the micropython hack is more versatile and can even be made transparent for same host files.

**Comment by embeddedt** [comment]
@pmp-p Why can't we unmount the default MEMFS ramdisk and mount BrowserFS at the root instead?

**Comment by pmp-p** [comment]
that would probably have impact on mkstemp() and friends since XmlHttpRequest is read only unless big changes, or it would have still to be mounted in a subfolder of BrowserFS itself.

**Comment by embeddedt** [comment]
@pmp-p Where is `mkstemp` used in our port? We shouldn't need read-write functionality.

**Comment by pmp-p** [comment]
@embeddedt it have no idea how to do a pivot_root,  FS.unmount("/") does not seem to work ...

**Comment by embeddedt** [comment]
I've discovered that it's not possible to mount a different filesystem to `/` in Emscripten at the moment. 

https://github.com/emscripten-core/emscripten/issues/2040

**Comment by pmp-p** [comment]
meh patching anything in emscripten scares me !

**Comment by embeddedt** [comment]
It would be unwise to patch anything in Emscripten because not everyone will have the patches in their version of the SDK.

Evidently it must not be a highly requested feature as the issue has been open for 5 years.

**Comment by pmp-p** [comment]
patching both Emscripten and BrowserFS seems unwise, basic file access with one C and 1 JS small file seems easier, though I know there are a lot of file access cases uncovered i think it's enough to start showcasing.

 I think maybe making the server files access transparent when accessing path that don't start with a / would give more compatibility with "desktop" scripts.

**Comment by embeddedt** [comment]
@pmp-p Can you get `import` working with this PR in its current state?

**Comment by pmp-p** [comment]
yes in the end the import PR would use the same javascript function via wasm_file_open/exists

**Comment by amirgon** [comment]
I would like to suggest a different approach.   

What if we provide a "root path" in the URL, and **load in advance all files under this root path into local storage** when the page loads?   

After doing that, we could use BrowserFS with `LocalStorage` backend, and all `XMLHttpRequest` can be done in advance in pure javascript when the page loads.  

In my opinion this could be a good enough solution for our problem.  
@embeddedt @pmp-p What do you think?

**Comment by pmp-p** [comment]
@amirgon that's almost what you get when you preload a zip file asynchronously and mount it via BrowserFS, for big assets files this is indeed the best approach. 

But does micropython or lvgl need to access to big static files, .py and .mpy are very small ? XMLHttpRequest and its static files lists seem a bit annoying for developpers who just want to showcase dynamically a work in progress.

Also doing that would probably slow down things for python imports since they are synchronous :
you could not go into code that does import until all .py are loaded in case of recursive imports.

**Comment by amirgon** [comment]
> @amirgon that's almost what you get when you preload a zip file asynchronously and mount it via BrowserFS, for big assets files this is indeed the best approach.
> 

@pmp-p The difference is that the user won't have to pack files in zip. Just upload them to gist, or anywhere they can be accessed by `GET` request.

> But does micropython or lvgl need to access to big static files, .py and .mpy are very small ? XMLHttpRequest and its static files lists seem a bit annoying for developpers who just want to showcase dynamically a work in progress.

`.py` files are small, image files and font files might be bigger, but not very big.  

For developers the experience should be something like:

- Put some files on github, gist, or someplace else accessible publicly by `GET` request
- Compose a URL that runs Micropython+lvgl with their script and a mounted root to their imported files. A web page could provide a form that would help them compose the URL according to their script, root dir, etc. (provide the URL they could share).
- Share that URL in forums, github issues etc.

> 
> Also doing that would probably slow down things for python imports since they are synchronous :
> you could not go into code that does import until all .py are loaded in case of recursive imports.

I don't think this is an issue at all.
No big deal if the web page loads a few files before it runs Emscripten. It's not different from using CDN.

**Comment by pmp-p** [comment]
> Compose a URL that runs Micropython+lvgl with their script and a mounted root to their imported files

Then maybe provide an online tool to pack files for https://emscripten.org/docs/api_reference/Filesystem-API.html#FS.mount, there's a python script to create those packages in emsdk.
Then use the script url to mount it and search for boot.py/main.py in it or specify it as an anchor. subfolder mount would not be a big problem in that case.

iirc there was a proposal for cpython to embed assets in zip mounted files that zipimport can use.
i think having both ways via micropython open() and package mount would satisfy most use case
either using simulator in continuous integration and url sharing for showcasing.

**Comment by amirgon** [comment]
> Then maybe provide an online tool to pack files for https://emscripten.org/docs/api_reference/Filesystem-API.html#FS.mount, there's a python script to create those packages in emsdk.

I think it's better to have the files available for browsing, than packing them. When they are read unpacked they can be changed without re-packing them.

> Then use the script url to mount it and search for boot.py/main.py in it or specify it as an anchor. subfolder mount would not be a big problem in that case.

Actually the script we want to run is supposed to encoded in the URL itself, not packed. This allows using an online editor to change it online and re-run emsripten with the changes, without any re-packing.

**Comment by pmp-p** [comment]
> I think it's better to have the files available for browsing, than packing them.

but to browse them you would need an index.

unpacking an encoded url to local file is not a big deal, even multiple times ( maybe associated with the soft reset function ? ), the only problem would be choosing a browser friendly encoding/decoding method and a type of archive that gives a file index and their sizes.


https://github.com/emscripten-core/emscripten/issues/2047

**Comment by embeddedt** [comment]
Why do we need to browse files at all? As far as I can tell there is no need to actually list the available files; we just need a way to load them.

At the simplest level we just need to wrap XMLHttpRequests in a synchronous wrapper. We can already retrieve gists using that. This looks like something Emterpreter could be necessary for?

**Comment by pmp-p** [comment]
@embeddedt Emterpreter is good for things like "time.sleep" even though it's really killing perfs ( at least with asyncio on my port, can't say for javascript port i did not test since i want perf. ).

 i also tried to donwload a file while putting micropython to sleep but it has frozen chromium so it could need time to get that working and need testing on all browsers. 
 i guess it would need a combination of workerfs for the download and emterpreter sleeping for an unlock

**Comment by embeddedt** [comment]
@pmp-p I thought that not all code needs to be run through Emterpreter. Ideally only the file access code needs to use it.

Wouldn't the execution flow be like this?

1. `read()` equivalent is called on an HTTP file.
2. JavaScript suspends Emterpreter execution.
3. XMLHttpRequest is issued.
4. XMLHttpRequest returns with error or contents of file.
5. XMLHttpRequest callback resumes Emterpreter execution.
6. `read()` returns to the caller.

**Comment by amirgon** [comment]
> but to browse them you would need an index.
> 
> unpacking an encoded url to local file is not a big deal, even multiple times ( maybe associated with the soft reset function ? ), the only problem would be choosing a browser friendly encoding/decoding method and a type of archive that gives a file index and their sizes.

If we encode the entire packed file-system in the URL, it could really give as a self contained micropython environment with its file system, that could be shared by a (rather long) URL!

We would need to be able to edit any file in that file system with the online editor on the web page, and re-pack the entire file system to provide a new shareable URL.

**Comment by embeddedt** [comment]
The encoding idea could work, but doesn't fit with @amirgon's original goal: to be able to import external HTTP links as scripts without needing to do any extra packing in the online editor.

**Comment by pmp-p** [comment]
> Ideally only the file access code needs to use it.
that maybe be true for C/C++ code, but read happens while inside the python vm interpreter any time. i could be very wrong but i think the whole bytecode loop must be async'ified

https://github.com/beuc surely knows better about that matter since he seems to have solved problem for cpython 2.7.

i think an hybrid solution : unpack static assets + read python code via XHR when needed is the simplest way while keeping decent speed all the time ( i used that for panda3d + python3 and it works fine,  though i won't publish before cpython 3.8 final).

 maybe  have script= &assets= in url and only reload script after that (like a soft reset but keeping MEMFS intact and editable  ) ?

**Comment by embeddedt** [comment]
> unpack static assets

But do we have any static assets at the moment? It seems to me that everything is going to come from XHRs.

**Comment by pmp-p** [comment]
XHR for *.py is allowed since it is text,    .mpy/images/anything binary should go via async fetch.

but indeed KISS way is all binary XHR, no index and expect every text file to be regular utf-8 ...

HEAD tell you if server is ok very quickly and hammering can be leveraged i'm working on that currently.

**Comment by embeddedt** [comment]
> XHR for *.py is allowed since it is text, .mpy/images/anything binary should go via async fetch.

Why can't XHRs be [used for binaries](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data) as well?

**Comment by pmp-p** [comment]
> Why can't XHRs be used for binaries as well?

We **still** can ( and i do in the js snippet of the PR ) but **we should not** because ```[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.```

meanwhile i've made some progress with packages/names import, i found that it's possible to guess folder existence anticipating the requests for __init__.py or an index.html, i still need to add code to recreate the matching paths in MEMFS

**Comment by pmp-p** [comment]
found the import bug, so i added relevant bits, maybe need to add some .c from py/ to the list in makefile

File: ports/javascript/Makefile [hunk 2]
```diff
@@ -20,13 +20,23 @@ BOTH_CFLAGS := -s WASM=0
...
+#for lvgl
+CPPFLAGS += -I$(EM_CACHE)/asmjs/ports-builds/sdl2/include
+
+ifdef WASM_FILE_API
+	CPPFLAGS += -DWASM_FILE_API=1 
+endif
+
 ifdef EMSCRIPTEN
-    CPP += -isystem $(EMSCRIPTEN)/system/include/libc -isystem $(EMSCRIPTEN)/system/include/libcxx -isystem $(EM_CACHE)/asmjs/ports-builds/sdl2/include -isystem $(EMSCRIPTEN)/system/include
+    CPP += --sysroot $(EMSCRIPTEN)/system
```
Comment (embeddedt) [inline ports/javascript/Makefile]: The `sysroot` line makes Emscripten fail to find SDL2 includes. My original method seems to work fine.

```suggestion
-    CPP += --sysroot $(EMSCRIPTEN)/system
+   CPP += -isystem $(EMSCRIPTEN)/system/include
```

File: ports/javascript/wasm_file_api.c [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+int
+wasm_file_open(const char *url) {
+    fprintf(stderr,"10:wasm_file_open[%s]\n", url);
+
+    if (strlen(url)>1 && url[0]==':') {
+        fprintf(stderr,"  -> same host[%s]\n", url);
+        int fidx = EM_ASM_INT({return wasm_file_open(UTF8ToString($0)); }, url );
+
+        // TODO rebuild local path in ramdisk relative to getcwd()
+        char fname[MICROPY_ALLOC_PATH_MAX];
```
Comment (embeddedt) [inline ports/javascript/wasm_file_api.c]: Referencing `MICROPY_ALLOC_PATH_MAX` requires `py/mpconfig.h` to be included.

**Comment by embeddedt** [comment]
@pmp-p I seem to be missing the JavaScript half of `wasm_file_open`. It is giving me a ReferenceError.

File: ports/javascript/Makefile (hunk 2 above)
Comment (pmp-p) [reply ports/javascript/Makefile]: fixed, i had forgot to add CPP += $(CPPFLAGS)

File: ports/javascript/wasm_file_api.c (hunk 3 above)
Comment (pmp-p) [reply ports/javascript/wasm_file_api.c]: indeed, added

**Comment by pmp-p** [comment]
the javascript part is in the documentation i did not know how to integrate it in javascript port since i use my port for testing features. 
https://github.com/pmp-p/micropython/blob/patch-8/ports/javascript/docs/wasm_file_api.txt

**Comment by embeddedt** [comment]
@pmp-p Thanks for the updates.

I am now trying to test it with this Python statement:

```py
f = open("https://gist.githubusercontent.com/embeddedt/1998334d3a75c62d257f7867a76a4960/raw/58140c9ea1e5453c5dee61509efa9fea632db42b/hello_world.py", "r")
f.read()
```

The call to `read()` fails with an error saying that `'NoneType' has no attribute `read'`. I'm probably missing some basic Python knowledge, any ideas?

**Comment by pmp-p** [comment]
weird your code works on my last sample which i based my PR from https://pmp-p.github.io/micropython/tui.html
```>>> f = open("https://gist.githubusercontent.com/embeddedt/1998334d3a75c62d257f7867a76a4960/raw/58140c9ea1e5453c5dee61509efa9fea632db42b/hello_world.py", "r")
>>> len(f.read())
20
>>> 
```

**Comment by pmp-p** [comment]
@embeddedt maybe you need to activate more options in your port in mpconfigport.h, i have quite a lot of thing on (1) that javascript port has not

**Comment by embeddedt** [comment]
@pmp-p I am trying `mpconfigport.h` now.

Spoke too soon on my last comment... just did a `make clean` and now it's broken again. Why do we need `sysroot`?

**Comment by pmp-p** [comment]
sysroot prevents clang from going into /usr/include, once it is done you can use ** normally ** -I to say where SDL and friends asmjs ports are. 
Also that way you don't have to expect people to know clang internals when most use gcc. see https://github.com/micropython/micropython/pull/4875#issuecomment-507123935

**Comment by embeddedt** [comment]
> you can use ** normally ** -I to say where SDL and friends asmjs ports are.

Well, using `-I` definitely doesn't work for me if `sysroot` is enabled. Evidently it is changing some other aspect of the include path list.

I checked and `-I$(EM_CACHE)/asmjs/ports-builds/sdl2/include` does exist.

On another note, I got `open()` working! I also tried `import`, but it failed due to a `SyntaxError` with the URL...

**Comment by pmp-p** [comment]
>  -I definitely doesn't work for me if sysroot is enabled

please could you run "emmake make check" with my makefile https://raw.githubusercontent.com/pmp-p/micropython-ports-wasm/master/Makefile , i still want to find a simple solution for user mods include.

my CPPFLAGS looks good and SDL2 folder is ok 
```user@pp /data/cross/micropython-cross/build/ports/wasm-xp $ emmake make check
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Makefile:150: warning: overriding recipe for target 'clean'
../../py/mkrules.mk:157: warning: ignoring old recipe for target 'clean'
Makefile:217: warning: overriding recipe for target 'micropython.html'
../../py/mkrules.mk:128: warning: ignoring old recipe for target 'micropython.html'
EMSDK=/opt/sdk/emsdk
EMSCRIPTEN=/opt/sdk/emsdk/fastcomp/emscripten
EMSDK_NODE=/opt/sdk/emsdk/node/8.9.1_64bit/bin/node
EMSCRIPTEN_TOOLS=/opt/sdk/emsdk/fastcomp/emscripten/tools
EM_CONFIG=/opt/sdk/emsdk/.emscripten
EMMAKEN_COMPILER=/opt/sdk/emsdk/fastcomp/fastcomp/bin/clang++
EMMAKEN_CFLAGS=
EM_CACHE=/opt/sdk/emsdk/.emscripten_cache
CPPFLAGS=-I/opt/sdk/emsdk/.emscripten_cache/asmjs/ports-builds/sdl2/include
EM_CACHE=/opt/sdk/emsdk/.emscripten_cache EMMAKEN_COMPILER=/opt/sdk/emsdk/fastcomp/fastcomp/bin/clang++ EMSCRIPTEN_TOOLS=/opt/sdk/emsdk/fastcomp/emscripten/tools EM_CONFIG=/opt/sdk/emsdk/.emscripten EMSDK_NODE=/opt/sdk/emsdk/node/8.9.1_64bit/bin/node EMSCRIPTEN=/opt/sdk/emsdk/fastcomp/emscripten EMSDK=/opt/sdk/emsdk EMMAKEN_CFLAGS=
Using [clang -E -D__CPP__ -D__EMSCRIPTEN__ --sysroot /opt/sdk/emsdk/fastcomp/emscripten/system -isystem /opt/sdk/emsdk/fastcomp/emscripten/system/include/libc -isystem /opt/sdk/emsdk/fastcomp/emscripten/system/include/libcxx -I/opt/sdk/emsdk/.emscripten_cache/asmjs/ports-builds/sdl2/include -U__i386 -U__i386 -Ui386 -U__SSE -U__SSE_MATH -U__SSE2 -U__SSE2_MATH -U__MMX__ -U__SSE__ -U__SSE_MATH__ -U__SSE2__ -U__SSE2_MATH__] as prepro

**Comment by embeddedt** [comment]
```
EMSDK=/work/emsdk
EMSCRIPTEN=/work/emsdk/emscripten/1.38.25
EMSDK_NODE=/work/emsdk/node/8.9.1_64bit/bin/node
EMSCRIPTEN_TOOLS=/work/emsdk/emscripten/1.38.25/tools
EM_CONFIG=/home/tt/.emscripten
EMMAKEN_COMPILER=/work/emsdk/clang/e1.38.25_64bit/clang++
EMMAKEN_CFLAGS=
EM_CACHE=
CPPFLAGS=-I/asmjs/ports-builds/sdl2/include
EMMAKEN_COMPILER=/work/emsdk/clang/e1.38.25_64bit/clang++ EMSCRIPTEN_NATIVE_OPTIMIZER=/work/emsdk/clang/e1.38.25_64bit/optimizer EMSCRIPTEN_TOOLS=/work/emsdk/emscripten/1.38.25/tools EM_CONFIG=/home/tt/.emscripten EMSDK_NODE=/work/emsdk/node/8.9.1_64bit/bin/node EMSCRIPTEN=/work/emsdk/emscripten/1.38.25 EMSDK=/work/emsdk EMMAKEN_CFLAGS=
Using [clang -E -D__CPP__ -D__EMSCRIPTEN__ --sysroot /work/emsdk/emscripten/1.38.25/system -isystem /work/emsdk/emscripten/1.38.25/system/include/libc -isystem /work/emsdk/emscripten/1.38.25/system/include/libcxx -I/asmjs/ports-builds/sdl2/include -U__i386 -U__i386 -Ui386 -U__SSE -U__SSE_MATH -U__SSE2 -U__SSE2_MATH -U__MMX__ -U__SSE__ -U__SSE_MATH__ -U__SSE2__ -U__SSE2_MATH__] as prepro
```

**Comment by pmp-p** [comment]
so i guess EM_CACHE should be EM_CONFIG

import will need that PR applied https://github.com/micropython/micropython/pull/4897 
or add code in javascript port to use POSIX file reader function ( which i find to complicate things a lot we have plenty of ram

**Comment by embeddedt** [comment]
> so i guess EM_CACHE should be EM_CONFIG

I don't understand exactly what you're suggesting.

> import will need that PR applied micropython#4897

Okay, since I am currently playing with it on a separate `pmpp_test` branch (and not our real `master` branch), I can merge that PR temporarily.

**Comment by pmp-p** [comment]
> I don't understand exactly what you're suggesting.
neither do i, temperature's goind to hot here :p
i forgot to init EM_CACHE its default,

i think i forgot  to add CPPFLAGS to CFLAGS somewhere in Makefile

**Comment by pmp-p** [comment]
forgot -D__EMSCRIPTEN__ in preprocessor command maybe it's masking sdl2

**Comment by pmp-p** [comment]
@embeddedt , on a clean install SDL2 maybe won't be there because if preprocessor is the first to be called  then SDL2 port won't be built. that's emcc that does the job.

**Comment by embeddedt** [comment]
@pmp-p As I stated before, SDL2 seems to work if I don't use `--sysroot`. I am not using a clean install - this is the same Emscripten SDK that I've been using for months.

**Comment by embeddedt** [comment]
No dice... still doesn't work. I'll try your other suggestion (comparing the Makefiles).

**Comment by embeddedt** [comment]
@pmp-p The reason your build is working is because you do not use SDL in any of your files. If I add `#include <SDL2/SDL.h>` to a random file (I picked `modos.c`) I get the same error on your port.

**Comment by pmp-p** [comment]
my port won't use SDL2 unless LVGL=1 is specified but i'll double check.
meanwhile i removed SDL2 from my host and i took an old emsdk and rebuilt https://github.com/pmp-p/micropython ( patch-8 ) without any problem. so i'm clueless.

could you please paste error log ?

**Comment by embeddedt** [comment]
```
modos.c:43:10: fatal error: 'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^~~~~~~~~~~~
```

I'm not sure that the benefits of using `--sysroot` outweigh the pitfalls.

**Comment by pmp-p** [comment]
patch-8 is not my port it's against lv_micropython and all lvgl compilation went ok
https://wyz.fr/56N

**Comment by embeddedt** [comment]
Found (one) workaround.

If you switch SDL from `-I` to `-isystem` it works even with `sysroot`!

**Comment by pmp-p** [comment]
@embeddedt  indeed maybe use ```#include "SDL2/SDL.h"``` instead <> are for system includes !

**Comment by embeddedt** [comment]
> <> are for system includes !

Unless I'm mistaken, `<>` is for global headers (whether added with `-I` or `-isystem`) and `""` is for headers in the current directory.

Anyway, I tried `""` and got the same error.

**Comment by pmp-p** [comment]
right https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html says either <> or "" should work both with -isystem or -I. 
is it only clang preprocessor failing or also emcc ?

**Comment by embeddedt** [comment]
I expect `emcc` to work because it does it's own magic for include paths. But it doesn't run until QSTR is generated, which requires `clang` to succeed.

So I can say with ~90% confidence that only clang will fail.

**Comment by pmp-p** [comment]
@embeddedt  could it be ~/ in EM_CACHE that pose problem ( my sdk is an absolute path) ?

**Comment by embeddedt** [comment]
@pmp-p Bingo! Replacing `~` with `$(HOME)` fixes the problem.

**Comment by embeddedt** [comment]
Glad that issue is resolved! :smiley:

I tried `import`, but it failed due to a `SyntaxError` with the URL... any thoughts?

**Comment by pmp-p** [comment]
no idea for import, this is still a WIP in my own port i'm not sure that PR is complete enough for that, was it a file/package/namespace import ? also there's once again some mpconfigport options to set.
iirc at least  MICROPY_ENABLE_EXTERNAL_IMPORT  MICROPY_ENABLE_COMPILER maybe MICROPY_PY_BUILTINS_COMPILE

**Comment by embeddedt** [comment]
All of which are set to `1` I think (I can check tomorrow). We just need to be able to import a file (so that the example can be separate from the driver initialization or something like that, @amirgon can clarify).

**Comment by pmp-p** [comment]
does that work ?
```
with open('hello.py','w') as f:
    f.write("print('hello')\n")
import sys
sys.path.insert(0,'')
import hello
```

**Comment by embeddedt** [comment]
It complains: "module not found". I also tried with `__import__("hello.py")` but it gave the same error.

**Comment by pmp-p** [comment]
I think we should keep import for a separate PR since the basic blocks for it are in this one : I picked up  a lot of MICROPY_READER_POSIX dependant functions separately it's messy in my port.

if you could put the javascript bits at the convenient place and document how to store a file for MEMFS that would be nice ( i used a fixed folder named "assets" after android apk structure for script compatibility ).
 maybe add the demo with the picture file with a one liner to start it as web not node.js on linux  ?

 Once you'd have choosen a way to do the --preload-file . i will be able to test and track what's missing for import  : first memfs then remote.

**Comment by embeddedt** [comment]
@pmp-p Our goal is not to preload any files, but rather to allow importing them from an arbritary URL.

**Comment by pmp-p** [comment]
then don't preload the picture, just serve it via web too. really, i'm begging for you to add a working web sample in javascript port :D. i find the "Running with HTML" of readme a bit dry ...

**Comment by embeddedt** [comment]
> i'm begging for you to add a working web sample in javascript port

It can already be run on the web.

Here's one example which uses a Python array for the image bitmap.

https://cdn.statically.io/gh/littlevgl/lv_micropython/0faa3db98/ports/javascript/lvgl_editor.html?env=dev&script=https://gist.githubusercontent.com/amirgon/764a2f14f403d62d46ca61d7e0546042/raw/f963e607d73f96ba793caaf2287e4ea3f7728562/lv_img_example1.py

**Comment by pmp-p** [comment]
> It can already be run on the web.

indeed but i failed locally, here are my steps :
- i created a file test.py next to lvgl_editor.html
- i started  ```python3.7 -m http.server``` to serve file from .
- opened http://127.0.0.1:8000/lvgl_editor.html?env=dev&script=test.py or ```http://127.0.0.1:8000/lvgl_editor.html?env=dev&script=http://127.0.0.1:8000/test.py```
with no script parameter it tries a online url and say 
```GET https://raw.githubusercontent.com/littlevgl/lv_binding_micropython/dev-6.0/examples/advanced_demo.py
lvgl_editor.html?env=dev:165
undefined
lvgl_editor.html?env=dev:170
Script passed: false
lvgl_editor.html?env=dev:217
Uncaught TypeError: iframe.contentWindow.mp_js_process_char is not a function
    at P.<anonymous> (lvgl_editor.html?env=dev:217)
    at P.l.emit (xterm.min.js:1)
    at xterm.min.js:1
    at n.fire (xterm.min.js:1)
    at P.handler (xterm.min.js:1)
    at P._keyDown (xterm.min.js:1)
    at HTMLTextAreaElement.<anonymous> (xterm.min.js:1)
```
i get no working repl

**Comment by embeddedt** [comment]
Why is https://github.com/littlevgl/lv_micropython/pull/6/commits/455fbb57915127075895709b58cda207bdd4ebe8 necessary? You can already get a REPL by running a blank script.

**Comment by pmp-p** [comment]
well i got repl to work based on the simpler sample you had here https://embeddedt.github.io/lv_micropython/ports/javascript/lvgl.html and i find it easier to get with. 
Anyway there can never be enough samples no   ?   and the truth is i really wanted ctrl+L working :p 

 now that i can run tests i'll try to start a an import hooks PR.

**Comment by embeddedt** [comment]
> simpler sample you had here https://embeddedt.github.io/lv_micropython/ports/javascript/lvgl.html

That is unmaintained and only works with LittlevGL 5.3.

> Anyway there can never be enough samples no?

The goal is not necessarily for this to be a sample (the `unix` port already does a good job at that) but rather to create an online simulator.

> and the truth is i really wanted ctrl+L working

What feature is this? Let me know and I will add it to my version.

**Comment by pmp-p** [comment]
ctrl+l clears screen of xterm.js without trashing current repl entry

**Comment by pmp-p** [comment]
@embeddedt i see that the importer i will try to PR is going to be quite independant from file support and further changes may be irrelevant.
are you ok with this one ?

**Comment by embeddedt** [comment]
@pmp-p I think the issues with building the REPL were because you aren't building against the working `pmpp_test` branch. I discovered some issues on the `master` branch and fixed them on `pmpp_test` (but hadn't merged my fixes back yet).

> are you ok with this one ?

Seems to be working fine on my end. I will merge it manually. I guess in the meantime we can discuss stuff on littlevgl/lvgl#792.

**Comment by embeddedt** [comment]
@pmp-p Before I close this, can you try building the `pmpp_test` branch so that I know it works? I'd really like to avoid maintaining multiple HTML interfaces.

**Comment by embeddedt** [comment]
Whoops, just realized I had a bunch of unpushed changes to `pmpp_test`. Please pull it again before you try building.

**Comment by embeddedt** [comment]
@pmp-p I've given you write access to the `pmpp_test` branch so that you don't have to make a new pull request for each set of changes.

**Comment by pmp-p** [comment]
@embeddedt thanks, it seems there's still some to fix

**Comment by pmp-p** [comment]
the pmpp_test branch seems ok with file handling. and it has a basic support for importing files.

**Comment by embeddedt** [comment]
@pmp-p Can I remove `repl.html` (does `lvgl_editor.html` build normally now)?

**Comment by pmp-p** [comment]
sure, it was just a test tool cause i had trouble with lvgl_editor running locally (http) and refusing to open https urls as a browser restriction (i use chromium flavour of chrome) ...

I did not test lvgl_editor yet but i intend to !
